homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.index, name='index'),
    path('addEvent/', views.addEvent, name='addEvent'),
    path('addMember/<int:id>', views.addMember, name='addMember'),
    path('deleteMember/<int:id>', views.deleteMember, name='deleteMember'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Event(models.Model):
    name = models.CharField('Event Name', max_length=25)
    deskripsi = models.TextField('Description', blank=True)

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField('Name', max_length=25)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class CreateEvent(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'deskripsi']

class CreateMember(ModelForm):
    class Meta:
        model = Member
        fields = ['name']

homepage/views.py
from django.shortcuts import render, redirect
from .models import Event, Member, CreateEvent, CreateMember

# Create your views here.
def index(request):
    event = Event.objects.all()
    member = Member.objects.all()

    return render(request, 'index.html', {'events' : event, "member" : member})

def addEvent(request):
    if request.method == 'POST':
        form = CreateEvent(request.POST)

        if form.is_valid():
            form.save()
            return redirect('homepage:index')
    else:
        form = CreateEvent()

    return render(request, 'addEvent.html', {'form' : form})


def addMember(request, id):

    if request.method == 'POST':
        form = CreateMember(request.POST)

        if form.is_valid():
            form = Member(event = Event.objects.get(id = id), name = form.data['name'])
            form.save()
            return redirect('homepage:index')
    else:
        form = CreateMember()
            
    return render(request, 'addMember.html', {'form': form})

def deleteMember(request, id):

    buck = Member.objects.get(id = id)
    buck.delete()

    return redirect('homepage:index')

homepage/templates/addEvent.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container">
    <form class="form-control" action="#" method="POST">
        {% csrf_token %}

        {{form|crispy}}
        <button type="submit" class="btn btn-outline-success btn-block">Add</button>
    </form>
  
  </div>
{% endblock %}

homepage/templates/addMember.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container">
    <form class="form-control" action="#" method="POST">
        {% csrf_token %}

        {{form|crispy}}
        <button type="submit" class="btn btn-outline-success btn-block">Add</button>
    </form>
  
  </div>
{% endblock %}

homepage/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Story 6</title>
  </head>
  <body>

    {% include 'navbar.html' %}

    {% block body %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/index.html
{% extends 'base.html' %}

{% block body %}
  <div class="container">
    <div class="container">
      <a href="{% url 'homepage:addEvent' %}" class="text-white">
        <button class="btn btn-outline-success btn-block">Add New Event</button>
      </a>
    </div>

    <div class="container">
        {% for x in events %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope='col' colspan="2" class="text-center"> <b> {{ x.name }} </b> </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            {% for y in member %}

              {% if y.event == x %}
                <tr>

                  <td align="left"> {{ y.name }} </td>
                  <td align="right">
                    <a href="deleteMember/{{ y.id }}" class="text-white"><button class="btn btn-outline-danger">X</button></a>
                  </td>

                </tr>
              {% endif %}

            {% endfor %}

          </tr>
        </tbody>
      </table>

    <div class="section-title mx-auto text-center"> 
      <a href="addMember/{{ x.id }}" class="text-white"><button class="btn btn-outline-success">Register</button></a>
    </div>
    {% endfor %}
    </div>
  
  </div>
{% endblock %}

homepage/templates/navbar.html
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="http://icons.iconarchive.com/icons/fruityth1ng/stark/512/Pictures-B-icon.png" width="30" height="30" class="d-inline-block align-top" alt="">
    Secret
  </a>
</nav>